environments: 
  develop:
  production:
  staging:
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
---
releases:
  - name: glycoflow
    namespace: {{ .Environment.Name }}
    chart: ../chart
    version: 0.1.0
    values:
      - {{ .Environment.Name }}/values.yml