name: Staging Release (tag)

on:
  workflow_call:
    inputs:
      release-version:
        description: 'Release version'
        required: true
        type: string
    

# Update Chart
# Build and Push
# Create Release
# Sync Infrastructure

jobs:
  update-helmfile:
    uses: libreconnect/actions/.github/workflows/update-helmfile.yml@main
    with:
      environment: staging
      release-version: ${{ github.ref_name }}
      repository: libreconnect/glycoflow
    secrets: inherit
  tag-release:
    runs-on: ubuntu-latest
    needs: [update-helmfile]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: libreconnect/glycoflow
          ref: main
          token: ${{ secrets.PAT }}
      - name: Tag Branches
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a ${{ inputs.release-version }} -m "Tagging ${{ inputs.release-version }}"
          git push origin ${{ inputs.release-version }}
  create-release:
    runs-on: ubuntu-latest
    needs: [update-helmfile]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          ref: ${{ inputs.release-version }}
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: true
  # build-and-push:
  #   uses: libreconnect/actions/.github/workflows/build-and-push.yml@main
  #   needs: [create-release, update-helmfile]
  #   with:
  #     image-name: libreconnect/glycoflow
  #     dockerfile: Dockerfile
  #     build-args: ""
  #     tag: main
